let particles = [];
let word = "FOG";
let fontSize = 100;
let mouseProximityThreshold = 150; 
let textPosition;
let textBounds; 
let textOpacity = 255; 

function setup() {
  createCanvas(windowWidth, windowHeight);
  textSize(fontSize);
  textAlign(CENTER, CENTER);
  textFont('sans-serif'); 
  textPosition = createVector(width / 2, height / 2);
  textBounds = {
    x: textPosition.x - 200,
    y: textPosition.y - fontSize / 2,
    w: 400,
    h: fontSize
  };
}

function draw() {
  background(0);

  let mousePosition = createVector(mouseX, mouseY);
  let mouseOverText = isMouseOverText(mouseX, mouseY, textBounds);
  if (mousePosition.dist(textPosition) < mouseProximityThreshold || mouseOverText) {
    textOpacity -= 5; 
    textOpacity = max(textOpacity, 0); 
    
    for (let i = 0; i < 10 && particles.length < 1000; i++) {
      particles.push(new Particle(textPosition.x + random(-250, 250), textPosition.y + random(-100, 100)));
    }
  } else {
    textOpacity = 255; 
  }
  particles = particles.filter(particle => {
    particle.update();
    particle.show();
    return !particle.isFinished();
  });

  fill(255, textOpacity);
  noStroke();
  if (particles.length < 500) {
    text(word, textPosition.x, textPosition.y);
  }
}

function isMouseOverText(x, y, bounds) {
  return x > bounds.x && x < bounds.x + bounds.w && y > bounds.y && y < bounds.y + bounds.h;
}

class Particle {
  constructor(x, y) {
    this.position = createVector(x, y);
    this.velocity = p5.Vector.random2D();
    this.velocity.setMag(random(2, 5));
    this.acceleration = createVector(0, 0.05); 
    this.lifespan = 255; 
  }

  update() {
    this.velocity.add(this.acceleration);
    this.position.add(this.velocity);
    this.lifespan -= 4; 
  }

  show() {
    noStroke();
    fill(255, this.lifespan);
    ellipse(this.position.x, this.position.y, 4);
  }

  isFinished() {
    return this.lifespan < 0;
  }
}

//Attribution: Code above was partially generated by ChatGPT